/** Static mapping from exercise slug → muscle group label (Italian). */
export type MuscleGroup = "Petto" | "Spalle" | "Schiena" | "Tricipiti" | "Bicipiti" | "Gambe" | "Addome" | "Altro";

export const MUSCLE_GROUPS: MuscleGroup[] = [
  "Petto",
  "Spalle",
  "Schiena",
  "Bicipiti",
  "Tricipiti",
  "Gambe",
  "Addome"
];

const map: Record<string, MuscleGroup> = {
  // Petto
  bench_press: "Petto",
  barbell_bench_press: "Petto",
  dumbbell_bench_press: "Petto",
  chest_press: "Petto",
  incline_bench_press: "Petto",
  decline_bench_press: "Petto",
  close_grip_bench_press: "Petto",
  machine_chest_press: "Petto",
  push_up: "Petto",
  knee_push_up: "Petto",
  diamond_push_up: "Petto",
  dip: "Petto",
  chest_dip: "Petto",
  bench_dip: "Petto",
  chest_fly: "Petto",
  dumbbell_fly: "Petto",
  incline_dumbbell_fly: "Petto",
  decline_dumbbell_fly: "Petto",
  cable_crossover: "Petto",
  pec_deck: "Petto",
  machine_fly: "Petto",
  pullover: "Petto",

  // Spalle
  overhead_press: "Spalle",
  seated_shoulder_press: "Spalle",
  dumbbell_shoulder_press: "Spalle",
  machine_shoulder_press: "Spalle",
  arnold_press: "Spalle",
  push_press: "Spalle",
  landmine_press: "Spalle",
  handstand_push_up: "Spalle",
  lateral_raise: "Spalle",
  front_raise: "Spalle",
  rear_delt_raise: "Spalle",
  bent_press: "Spalle",

  // Schiena
  pull_up: "Schiena",
  chin_up: "Schiena",
  neutral_grip_pull_up: "Schiena",
  assisted_pull_up: "Schiena",
  lat_pulldown: "Schiena",
  close_grip_lat_pulldown: "Schiena",
  reverse_grip_lat_pulldown: "Schiena",
  straight_arm_pulldown: "Schiena",
  muscle_up: "Schiena",
  rope_climb: "Schiena",
  bent_over_row: "Schiena",
  barbell_row: "Schiena",
  one_arm_dumbbell_row: "Schiena",
  chest_supported_row: "Schiena",
  seated_cable_row: "Schiena",
  low_row_machine: "Schiena",
  t_bar_row: "Schiena",
  inverted_row: "Schiena",
  face_pull: "Schiena",
  rear_delt_fly: "Schiena",
  reverse_pec_deck: "Schiena",
  shoulder_shrug: "Schiena",
  upright_row: "Schiena",

  // Bicipiti
  biceps_curl: "Bicipiti",
  barbell_curl: "Bicipiti",
  dumbbell_curl: "Bicipiti",
  alternating_dumbbell_curl: "Bicipiti",
  hammer_curl: "Bicipiti",
  concentration_curl: "Bicipiti",
  preacher_curl: "Bicipiti",
  incline_dumbbell_curl: "Bicipiti",
  spider_curl: "Bicipiti",
  reverse_curl: "Bicipiti",
  zottman_curl: "Bicipiti",
  wrist_curl: "Bicipiti",
  reverse_wrist_curl: "Bicipiti",

  // Tricipiti
  overhead_triceps_extension: "Tricipiti",
  lying_triceps_extension: "Tricipiti",
  skull_crusher: "Tricipiti",
  seated_overhead_triceps_extension: "Tricipiti",
  triceps_pushdown: "Tricipiti",
  rope_pushdown: "Tricipiti",
  triceps_kickback: "Tricipiti",
  close_grip_push_up: "Tricipiti",

  // Gambe
  squat: "Gambe",
  back_squat: "Gambe",
  front_squat: "Gambe",
  goblet_squat: "Gambe",
  box_squat: "Gambe",
  hack_squat: "Gambe",
  smith_machine_squat: "Gambe",
  pistol_squat: "Gambe",
  wall_sit: "Gambe",
  bulgarian_split_squat: "Gambe",
  split_squat: "Gambe",
  lunge: "Gambe",
  reverse_lunge: "Gambe",
  walking_lunge: "Gambe",
  lateral_lunge: "Gambe",
  curtsy_lunge: "Gambe",
  step_up: "Gambe",
  leg_press: "Gambe",
  leg_extension: "Gambe",
  leg_curl: "Gambe",
  lying_leg_curl: "Gambe",
  seated_leg_curl: "Gambe",
  standing_leg_curl: "Gambe",
  nordic_hamstring_curl: "Gambe",
  glute_ham_raise: "Gambe",
  hip_thrust: "Gambe",
  glute_bridge: "Gambe",
  cable_kickback: "Gambe",
  calf_raise: "Gambe",
  standing_calf_raise: "Gambe",
  seated_calf_raise: "Gambe",
  donkey_calf_raise: "Gambe",
  adductor_machine: "Gambe",
  abductor_machine: "Gambe",
  hindu_squat: "Gambe",
  deadlift: "Gambe",
  conventional_deadlift: "Gambe",
  romanian_deadlift: "Gambe",
  stiff_legged_deadlift: "Gambe",
  sumo_deadlift: "Gambe",
  trap_bar_deadlift: "Gambe",
  rack_pull: "Gambe",
  good_morning: "Gambe",
  back_extension: "Gambe",
  reverse_hyperextension: "Gambe",
  kettlebell_swing: "Gambe",
  cable_pull_through: "Gambe",

  // Addome
  crunch: "Addome",
  bicycle_crunch: "Addome",
  reverse_crunch: "Addome",
  cable_crunch: "Addome",
  sit_up: "Addome",
  v_up: "Addome",
  jackknife: "Addome",
  leg_raise: "Addome",
  hanging_leg_raise: "Addome",
  hanging_knee_raise: "Addome",
  plank: "Addome",
  side_plank: "Addome",
  hollow_body_hold: "Addome",
  russian_twist: "Addome",
  mountain_climber: "Addome",
  superman: "Addome",
  side_bend: "Addome",
  ab_wheel_rollout: "Addome",
  pallof_press: "Addome",

  // Altro
  burpee: "Altro",
  squat_thrust: "Altro",
  bear_crawl: "Altro",
  jumping_jack: "Altro",
  jump_rope: "Altro",
  split_jump: "Altro",
  box_jump: "Altro",
  stair_climbing: "Altro",
  front_lever: "Altro",
  back_lever: "Altro",
  human_flag: "Altro",
  l_sit: "Altro",
  v_sit: "Altro",
  planche: "Altro",
  handstand: "Altro",
  crow_pose: "Altro",
  horse_stance: "Altro",
  bridge: "Altro",
  hindu_push_up: "Altro",
  one_arm_push_up: "Altro",
  one_arm_pull_up: "Altro",
  hand_walking: "Altro",
  dirty_dog: "Altro",
  donkey_kick: "Altro",
  kip_up: "Altro",
  snatch: "Altro",
  power_snatch: "Altro",
  muscle_snatch: "Altro",
  clean: "Altro",
  power_clean: "Altro",
  hang_clean: "Altro",
  clean_and_jerk: "Altro",
  jerk: "Altro",
  split_jerk: "Altro",
  push_jerk: "Altro",
  squat_jerk: "Altro",
  clean_and_press: "Altro",

};

export const getMuscleGroup = (slug: string): MuscleGroup =>
  map[slug] ?? "Altro";
